#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ogrenci_Iletisim_Projesi.Resource", IsApplication=true)]

namespace Ogrenci_Iletisim_Projesi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int ad = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ad_giris = 2131099650;
			
			// aapt resource value: 0x7f060019
			public const int btnGiris = 2131099673;
			
			// aapt resource value: 0x7f060015
			public const int btnKayit = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int btnSinif1 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int btnSinif2 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int btnSinif3 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int btnSinif4 = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int btnkayit = 2131099675;
			
			// aapt resource value: 0x7f060022
			public const int button1 = 2131099682;
			
			// aapt resource value: 0x7f060007
			public const int cinsiyet = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int e_mail = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int e_mail_giris = 2131099654;
			
			// aapt resource value: 0x7f060020
			public const int editText1 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int editText2 = 2131099681;
			
			// aapt resource value: 0x7f060016
			public const int k_adi = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int k_adi_girdi = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int k_sifre_girdi = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int kyd_text = 2131099674;
			
			// aapt resource value: 0x7f060000
			public const int listView1 = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int rd_akade = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int rd_bayan = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int rd_erkek = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int rd_group_cinsiyet = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int rd_ogr = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int rd_unvan_group = 2131099660;
			
			// aapt resource value: 0x7f060013
			public const int resim = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int resim_yolu = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int sifre = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int sifre_giris = 2131099666;
			
			// aapt resource value: 0x7f060003
			public const int soyad = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int soyad_giris = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int spin_bolum = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int spn_bolum = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int unvan = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dersler = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int KullaniciEkle = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Siniflar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Yorumlar = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
