//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace Ogrenci_Iletisim_Projesi.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://192.168.198.88")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BolumCekOperationCompleted;
        
        private System.Threading.SendOrPostCallback DersAdiCekOperationCompleted;
        
        private System.Threading.SendOrPostCallback DersIdCekOperationCompleted;
        
        private System.Threading.SendOrPostCallback GirisKontrolOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciIdGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciKayitOperationCompleted;
        
        private System.Threading.SendOrPostCallback YorumlariGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback YorumEkleOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciAdSoyadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://192.168.43.44/webservice/Service1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BolumCekCompletedEventHandler BolumCekCompleted;
        
        /// <remarks/>
        public event DersAdiCekCompletedEventHandler DersAdiCekCompleted;
        
        /// <remarks/>
        public event DersIdCekCompletedEventHandler DersIdCekCompleted;
        
        /// <remarks/>
        public event GirisKontrolCompletedEventHandler GirisKontrolCompleted;
        
        /// <remarks/>
        public event KullaniciIdGetirCompletedEventHandler KullaniciIdGetirCompleted;
        
        /// <remarks/>
        public event KullaniciKayitCompletedEventHandler KullaniciKayitCompleted;
        
        /// <remarks/>
        public event YorumlariGetirCompletedEventHandler YorumlariGetirCompleted;
        
        /// <remarks/>
        public event YorumEkleCompletedEventHandler YorumEkleCompleted;
        
        /// <remarks/>
        public event KullaniciAdSoyadCompletedEventHandler KullaniciAdSoyadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/BolumCek", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] BolumCek() {
            object[] results = this.Invoke("BolumCek", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void BolumCekAsync() {
            this.BolumCekAsync(null);
        }
        
        /// <remarks/>
        public void BolumCekAsync(object userState) {
            if ((this.BolumCekOperationCompleted == null)) {
                this.BolumCekOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBolumCekOperationCompleted);
            }
            this.InvokeAsync("BolumCek", new object[0], this.BolumCekOperationCompleted, userState);
        }
        
        private void OnBolumCekOperationCompleted(object arg) {
            if ((this.BolumCekCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BolumCekCompleted(this, new BolumCekCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/DersAdiCek", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] DersAdiCek(int bolum, int sinif) {
            object[] results = this.Invoke("DersAdiCek", new object[] {
                        bolum,
                        sinif});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void DersAdiCekAsync(int bolum, int sinif) {
            this.DersAdiCekAsync(bolum, sinif, null);
        }
        
        /// <remarks/>
        public void DersAdiCekAsync(int bolum, int sinif, object userState) {
            if ((this.DersAdiCekOperationCompleted == null)) {
                this.DersAdiCekOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDersAdiCekOperationCompleted);
            }
            this.InvokeAsync("DersAdiCek", new object[] {
                        bolum,
                        sinif}, this.DersAdiCekOperationCompleted, userState);
        }
        
        private void OnDersAdiCekOperationCompleted(object arg) {
            if ((this.DersAdiCekCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DersAdiCekCompleted(this, new DersAdiCekCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/DersIdCek", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] DersIdCek(int bolum, int sinif) {
            object[] results = this.Invoke("DersIdCek", new object[] {
                        bolum,
                        sinif});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void DersIdCekAsync(int bolum, int sinif) {
            this.DersIdCekAsync(bolum, sinif, null);
        }
        
        /// <remarks/>
        public void DersIdCekAsync(int bolum, int sinif, object userState) {
            if ((this.DersIdCekOperationCompleted == null)) {
                this.DersIdCekOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDersIdCekOperationCompleted);
            }
            this.InvokeAsync("DersIdCek", new object[] {
                        bolum,
                        sinif}, this.DersIdCekOperationCompleted, userState);
        }
        
        private void OnDersIdCekOperationCompleted(object arg) {
            if ((this.DersIdCekCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DersIdCekCompleted(this, new DersIdCekCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/GirisKontrol", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GirisKontrol(string ad_email, string sifre) {
            object[] results = this.Invoke("GirisKontrol", new object[] {
                        ad_email,
                        sifre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GirisKontrolAsync(string ad_email, string sifre) {
            this.GirisKontrolAsync(ad_email, sifre, null);
        }
        
        /// <remarks/>
        public void GirisKontrolAsync(string ad_email, string sifre, object userState) {
            if ((this.GirisKontrolOperationCompleted == null)) {
                this.GirisKontrolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGirisKontrolOperationCompleted);
            }
            this.InvokeAsync("GirisKontrol", new object[] {
                        ad_email,
                        sifre}, this.GirisKontrolOperationCompleted, userState);
        }
        
        private void OnGirisKontrolOperationCompleted(object arg) {
            if ((this.GirisKontrolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GirisKontrolCompleted(this, new GirisKontrolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/KullaniciIdGetir", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KullaniciIdGetir() {
            object[] results = this.Invoke("KullaniciIdGetir", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciIdGetirAsync() {
            this.KullaniciIdGetirAsync(null);
        }
        
        /// <remarks/>
        public void KullaniciIdGetirAsync(object userState) {
            if ((this.KullaniciIdGetirOperationCompleted == null)) {
                this.KullaniciIdGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciIdGetirOperationCompleted);
            }
            this.InvokeAsync("KullaniciIdGetir", new object[0], this.KullaniciIdGetirOperationCompleted, userState);
        }
        
        private void OnKullaniciIdGetirOperationCompleted(object arg) {
            if ((this.KullaniciIdGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciIdGetirCompleted(this, new KullaniciIdGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/KullaniciKayit", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KullaniciKayit(string isim, string soyisim, string mail, int cins, int unvan, int bolum, string sifre, string resim) {
            object[] results = this.Invoke("KullaniciKayit", new object[] {
                        isim,
                        soyisim,
                        mail,
                        cins,
                        unvan,
                        bolum,
                        sifre,
                        resim});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciKayitAsync(string isim, string soyisim, string mail, int cins, int unvan, int bolum, string sifre, string resim) {
            this.KullaniciKayitAsync(isim, soyisim, mail, cins, unvan, bolum, sifre, resim, null);
        }
        
        /// <remarks/>
        public void KullaniciKayitAsync(string isim, string soyisim, string mail, int cins, int unvan, int bolum, string sifre, string resim, object userState) {
            if ((this.KullaniciKayitOperationCompleted == null)) {
                this.KullaniciKayitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciKayitOperationCompleted);
            }
            this.InvokeAsync("KullaniciKayit", new object[] {
                        isim,
                        soyisim,
                        mail,
                        cins,
                        unvan,
                        bolum,
                        sifre,
                        resim}, this.KullaniciKayitOperationCompleted, userState);
        }
        
        private void OnKullaniciKayitOperationCompleted(object arg) {
            if ((this.KullaniciKayitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciKayitCompleted(this, new KullaniciKayitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/YorumlariGetir", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] YorumlariGetir(int ders_id) {
            object[] results = this.Invoke("YorumlariGetir", new object[] {
                        ders_id});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void YorumlariGetirAsync(int ders_id) {
            this.YorumlariGetirAsync(ders_id, null);
        }
        
        /// <remarks/>
        public void YorumlariGetirAsync(int ders_id, object userState) {
            if ((this.YorumlariGetirOperationCompleted == null)) {
                this.YorumlariGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYorumlariGetirOperationCompleted);
            }
            this.InvokeAsync("YorumlariGetir", new object[] {
                        ders_id}, this.YorumlariGetirOperationCompleted, userState);
        }
        
        private void OnYorumlariGetirOperationCompleted(object arg) {
            if ((this.YorumlariGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YorumlariGetirCompleted(this, new YorumlariGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/YorumEkle", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool YorumEkle(string yorum, string resim_yolu, int k_id, int ders_id) {
            object[] results = this.Invoke("YorumEkle", new object[] {
                        yorum,
                        resim_yolu,
                        k_id,
                        ders_id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void YorumEkleAsync(string yorum, string resim_yolu, int k_id, int ders_id) {
            this.YorumEkleAsync(yorum, resim_yolu, k_id, ders_id, null);
        }
        
        /// <remarks/>
        public void YorumEkleAsync(string yorum, string resim_yolu, int k_id, int ders_id, object userState) {
            if ((this.YorumEkleOperationCompleted == null)) {
                this.YorumEkleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYorumEkleOperationCompleted);
            }
            this.InvokeAsync("YorumEkle", new object[] {
                        yorum,
                        resim_yolu,
                        k_id,
                        ders_id}, this.YorumEkleOperationCompleted, userState);
        }
        
        private void OnYorumEkleOperationCompleted(object arg) {
            if ((this.YorumEkleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YorumEkleCompleted(this, new YorumEkleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.198.88/KullaniciAdSoyad", RequestNamespace="http://192.168.198.88", ResponseNamespace="http://192.168.198.88", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string KullaniciAdSoyad(int id) {
            object[] results = this.Invoke("KullaniciAdSoyad", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciAdSoyadAsync(int id) {
            this.KullaniciAdSoyadAsync(id, null);
        }
        
        /// <remarks/>
        public void KullaniciAdSoyadAsync(int id, object userState) {
            if ((this.KullaniciAdSoyadOperationCompleted == null)) {
                this.KullaniciAdSoyadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciAdSoyadOperationCompleted);
            }
            this.InvokeAsync("KullaniciAdSoyad", new object[] {
                        id}, this.KullaniciAdSoyadOperationCompleted, userState);
        }
        
        private void OnKullaniciAdSoyadOperationCompleted(object arg) {
            if ((this.KullaniciAdSoyadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciAdSoyadCompleted(this, new KullaniciAdSoyadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BolumCekCompletedEventHandler(object sender, BolumCekCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BolumCekCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BolumCekCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DersAdiCekCompletedEventHandler(object sender, DersAdiCekCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DersAdiCekCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DersAdiCekCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DersIdCekCompletedEventHandler(object sender, DersIdCekCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DersIdCekCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DersIdCekCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GirisKontrolCompletedEventHandler(object sender, GirisKontrolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GirisKontrolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GirisKontrolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void KullaniciIdGetirCompletedEventHandler(object sender, KullaniciIdGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciIdGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciIdGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void KullaniciKayitCompletedEventHandler(object sender, KullaniciKayitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciKayitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciKayitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void YorumlariGetirCompletedEventHandler(object sender, YorumlariGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YorumlariGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YorumlariGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void YorumEkleCompletedEventHandler(object sender, YorumEkleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YorumEkleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YorumEkleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void KullaniciAdSoyadCompletedEventHandler(object sender, KullaniciAdSoyadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciAdSoyadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciAdSoyadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591